# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 08:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_User',
            fields=[
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('addr', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='hospital_user',
            name='addr',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='hospital_user',
            name='tel',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='hospital_user',
            name='dong',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='hospital_user',
            name='gungu',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
