# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180228_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('subject', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='hospital_user',
            name='sido',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='hospital_user',
            name='subjects',
            field=models.ManyToManyField(to='accounts.Subject'),
        ),
    ]
