# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-05 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_auto_20180305_1335'),
        ('accounts', '0002_auto_20180228_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital_user',
            name='subjects',
            field=models.ManyToManyField(to='hospital.Subject'),
        ),
    ]
