# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180305_1349'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.AlterField(
            model_name='hospital_user',
            name='subjects',
            field=models.ManyToManyField(to='hospital.Subject'),
        ),
    ]
