# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180305_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital_user',
            name='subjects',
        ),
        migrations.AddField(
            model_name='personal_user',
            name='dong',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='personal_user',
            name='gungu',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='personal_user',
            name='sido',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
