# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 07:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180307_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital_user',
            name='addr',
        ),
        migrations.RemoveField(
            model_name='hospital_user',
            name='dong',
        ),
        migrations.RemoveField(
            model_name='hospital_user',
            name='gungu',
        ),
        migrations.RemoveField(
            model_name='hospital_user',
            name='sido',
        ),
        migrations.RemoveField(
            model_name='hospital_user',
            name='tel',
        ),
    ]
