# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-21 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20180221_2250'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reserve',
            unique_together=set([('hospital', 'date', 'time')]),
        ),
    ]
