# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-23 02:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20180223_0942'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reserve',
            unique_together=set([('hospital', 'doctor', 'date', 'time')]),
        ),
    ]
