# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-23 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_auto_20180223_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sidoCode', models.CharField(max_length=2)),
                ('sidoName', models.CharField(max_length=20)),
                ('gunguCode', models.CharField(max_length=5)),
                ('gunguName', models.CharField(max_length=20)),
            ],
        ),
    ]
