# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 06:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_sido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserve',
            options={'ordering': ['-date', '-time'], 'verbose_name': '예약내역'},
        ),
    ]
