# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_subject_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['code']},
        ),
        migrations.AddField(
            model_name='hospital',
            name='dong',
            field=models.CharField(default='마곡동', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='gungu',
            field=models.CharField(default='강서구', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='sido',
            field=models.CharField(default='서울', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
