# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_auto_20180302_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sido',
            name='gunguCode',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='sido',
            name='sidoCode',
            field=models.CharField(max_length=6),
        ),
    ]
