# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_hospital_sidogungu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='sidogungu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Sido'),
        ),
    ]
