# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-05 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_auto_20180302_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserve',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
