# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_auto_20180302_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='tel',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='sido',
            name='sidoCode',
            field=models.CharField(max_length=2),
        ),
    ]
