# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-05 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0014_auto_20180305_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
