# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180307_1640'),
        ('hospital', '0015_auto_20180308_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='user',
            field=models.ForeignKey(default='16', on_delete=django.db.models.deletion.CASCADE, to='accounts.Hospital_User'),
            preserve_default=False,
        ),
    ]
